### ISSUE TITLE
Recovery  sound  error

### ISSUE THREAD

**Issue by alexhjb001** [dsforza96/visual-mic#1]
I run it mac 
I get sound image is right 

![Figure_1](https://user-images.githubusercontent.com/53072613/82020437-a6d13280-96bb-11ea-8054-0a40c72f6ab8.png)

Recovery  sound  error

![image](https://user-images.githubusercontent.com/53072613/82020681-23fca780-96bc-11ea-8cc9-07e9513dd76f.png)

every recovery sound is nothing , i don't know why

**Comment by antoniomuso** [comment]
Have you tried to change sound player?We noted that some video player don't reproduce the recoveried sounds.

**Comment by alexhjb001** [comment]
Thank you.Change to 48 k Hz 24bit is ok.

**Comment by alexhjb001** [comment]
Hi,i have very old video.Can recovery sound？
[image: image.png]

**Comment by dsforza96** [comment]
Hi,
I don't know exactly what you mean by very old video, but for example its frame rate has to be higher (at least the double) than the sound frequency you want to recover.

If you want a more complete answer you can look at the web page of the original work (http://people.csail.mit.edu/mrub/VisualMic/), in particular in the FAQs section.

**Comment by alexhjb001** [comment]
Thank you
