### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by anmolduainter** [dsforza96/visual-mic#2]
I have run this on sample video.It is not working.

**Comment by antoniomuso** [comment]
Have you tried to plot the sound? You may have the same [issue](https://github.com/dsforza96/visual-mic/issues/1)

**Comment by anmolduainter** [comment]
I was getting Broadcasting Error. It seems there is a problem of addition(broadcasting error) in this section of code (sound += sig_aligned).After running on my sample video I checked that sound is initialized with zeroes 61 times but during addition align_vectors is returning array of 56 values thats why I am unable to proceed.

**Comment by anmolduainter** [comment]
Hi I have changed the code to this:
  sound = None
  for sig in signals.values():
    sig_aligned = align_vectors(np.array(sig), np.array(signals[(0, 0)]))  # With "residual_lowpass" same result
    if (sound is None):
      sound = sig_aligned
    else:
      sound += sig_aligned

Is it correct way? I noticed now that: 1. I got 1 sec recovered sound for 3 sec video(due to sampling rate). 2. I am unable to run the recovered file on my player.

**Comment by antoniomuso** [comment]
with which sample_rate do you call the program? and what is the real video sample rate?

**Comment by anmolduainter** [comment]
Currently No Sampling rate was given, CAP_PROP_FPS is only being used as in the code.

I tried to run last kit-kat sample video provided by them http://data.csail.mit.edu/vidmag/VisualMic/.
Can you please run on your end whether the sound plot is same as what they have defined, because I am not getting the same.

**Comment by antoniomuso** [comment]
Ok, If you pass the right sample rate 60 the program does not crush.
You have used the video with Rolling Shutter that is the only one not supported by our library.
